#!/bin/bash
echo "==========================================================="
echo "HMI code compiling..."
g++ -o BTReceive_edit BTReceive_edit.cpp -lbluetooth
echo "Compiling complete!"
echo "HMI starting..."
echo ""

python Main_Server_edit.py &
echo "Python TCP server on RPi started!"
echo ""
sleep 2

python Client.py &
echo "Python TCP client on walker started!"
echo "Touchscreen Ready! Awaiting commands..."
echo ""
sleep 2

./BTReceive_edit &
echo "C++ TCP client/Bluetooth server on RPi started!"
echo "Awaiting Bluetooth connection and commands..."
echo ""
